export { HomePage } from './HomePage';
export { LoginPage } from './LoginPage';
export { RegisterPage } from './RegisterPage';
export { DashboardPage } from './DashboardPage';
export { EditProfilePage } from './EditProfilePage';
export { MenuPage } from './MenuPage';
export { CheckoutPage } from './CheckoutPage';
export { OrderSuccessPage } from './OrderSuccessPage';
export { MyOrdersPage } from './MyOrdersPage';
export { AdminOrdersPage } from './AdminOrdersPage';
export { default as AdminStockPage } from './AdminStockPage';
export { default as AdminFinancePage } from './AdminFinancePage';
export { default as AdminDREPage } from './AdminDREPage';
export { default as AdminFluxoCaixaPage } from './AdminFluxoCaixaPage';
export { default as AdminBalancoPatrimonialPage } from './AdminBalancoPatrimonialPage';
export { default as AdminDespesasPage } from './AdminDespesasPage';
export { default as AdminManagePage } from './AdminManagePage';
